import React from 'react';
import { StyleSheet, View, Text, ScrollView, TouchableOpacity } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { ScreenKey } from '@medivo/types';

interface PrivacyPolicyScreenProps {
  onNavigate: (screen: ScreenKey) => void;
}

export function PrivacyPolicyScreen({ onNavigate }: PrivacyPolicyScreenProps) {
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <View style={styles.header}>
        <TouchableOpacity style={styles.backBtn} onPress={() => onNavigate('splash')}>
          <Feather name="arrow-left" size={20} color="#1E1B4B" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms & Privacy Policy</Text>
        <View style={{ width: 38 }} />
      </View>

      <View style={styles.heroBox}>
        <View style={styles.iconCircle}>
          <Feather name="shield" size={28} color="#059669" />
        </View>
        <Text style={styles.title}>HIPAA & Data Disclosures</Text>
        <Text style={styles.subtitle}>Medivo Health Intelligence is committed to securing your clinical telemetry data.</Text>
      </View>

      <View style={styles.sectionCard}>
        <View style={styles.cardHeader}>
          <Feather name="lock" size={18} color="#4338CA" />
          <Text style={styles.cardTitle}>1. Data Encryption & Storage</Text>
        </View>
        <Text style={styles.bodyText}>
          All facial scan images and health metrics are encrypted in transit via TLS 1.3 and at rest using AES-256 encryption. Raw camera frames are processed on-device and never stored permanently without explicit consent.
        </Text>
      </View>

      <View style={styles.sectionCard}>
        <View style={styles.cardHeader}>
          <Feather name="aperture" size={18} color="#0EA5E9" />
          <Text style={styles.cardTitle}>2. AI Model Telemetry Usage</Text>
        </View>
        <Text style={styles.bodyText}>
          Our AI diagnostic models use anonymized skin landmark telemetry solely for calculating hydration, pigmentation, and barrier scores. Your data is never sold to third-party advertisers.
        </Text>
      </View>

      <View style={styles.sectionCard}>
        <View style={styles.cardHeader}>
          <Feather name="user-check" size={18} color="#D97706" />
          <Text style={styles.cardTitle}>3. Telehealth & Doctor Consultations</Text>
        </View>
        <Text style={styles.bodyText}>
          Virtual video consultations are conducted over HIPAA-compliant encrypted WebRTC streams. Diagnostic reports generated by AI are made accessible only to your assigned board-certified dermatologist.
        </Text>
      </View>

      <View style={styles.sectionCard}>
        <View style={styles.cardHeader}>
          <Feather name="check-circle" size={18} color="#059669" />
          <Text style={styles.cardTitle}>4. User Rights & Data Deletion</Text>
        </View>
        <Text style={styles.bodyText}>
          You retain 100% ownership of your health records. You may export your diagnostic history or request full permanent account deletion at any time via your Profile Settings.
        </Text>
      </View>

      <TouchableOpacity style={styles.acceptBtn} onPress={() => onNavigate('splash')}>
        <Text style={styles.acceptBtnText}>Return to App</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAFC' },
  content: { padding: 24, paddingBottom: 40 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  backBtn: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#EEF0F7' },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#1E1B4B' },
  heroBox: { alignItems: 'center', marginBottom: 24 },
  iconCircle: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#ECFDF5', justifyContent: 'center', alignItems: 'center', marginBottom: 14 },
  title: { fontSize: 22, fontWeight: '800', color: '#1E1B4B', textAlign: 'center' },
  subtitle: { fontSize: 13, color: '#64748B', textAlign: 'center', marginTop: 4, lineHeight: 18 },
  sectionCard: { backgroundColor: '#FFFFFF', padding: 18, borderRadius: 20, borderWidth: 1, borderColor: '#EEF0F7', marginBottom: 14 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  cardTitle: { fontSize: 15, fontWeight: '700', color: '#1E1B4B', marginLeft: 8 },
  bodyText: { fontSize: 13, color: '#475569', lineHeight: 20 },
  acceptBtn: { backgroundColor: '#4338CA', paddingVertical: 16, borderRadius: 18, alignItems: 'center', marginTop: 10 },
  acceptBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 15 },
});
